version: '3'

services:
  app:
      image: paulolopesestevao/assinatura_digital_app
      build: .
      volumes: 
          - .:/assinatura
      working_dir: /assinatura
      container_name: assinatura_digital
      command: python signature.py